property:
  gpu-id: 0
  net-scale-factor: 1
  model-color-format: 1
  # onnx-file: pretrained/deepstream/yolox/yolox_s.pth.onnx
  # onnx-file: pretrained/deepstream/yolox/test_output_yolox_s_coco300_ch80.pth.onnx
  onnx-file: /mnt/data/pretrained/deepstream/yolox/test_output_yolox_s_coco300_ch80.pth.onnx
  # model-engine-file: /mnt/data/pretrained/deepstream/yolox/model_b1_gpu0_fp32.engine
  # model-engine-file: /home/colivier/src/DeepStream-Yolo/src/model_b1_gpu0_fp32.engine
  model-engine-file: /home/colivier/src/DeepStream-Yolo/src/model_b4_gpu0_fp32.engine
  # model-engine-file: model_b4_gpu0_fp32.engine
  labelfile-path: /mnt/data/pretrained/deepstream/yolox/labels_coco.txt
  # batch-size: 1
  # batch-size: 4
  network-mode: 0
  # num-detected-classes: 80
  num-detected-classes: 1
  interval: 0
  gie-unique-id: 1
  process-mode: 1
  network-type: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 0
  parse-bbox-func-name: NvDsInferParseYolo
  custom-lib-path: nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
  engine-create-func-name: NvDsInferYoloCudaEngineGet

class-attrs-all:
  nms-iou-threshold: 0.45
  pre-cluster-threshold: 0.25
  topk: 300
