#!/bin/bash
set -e
SCRIPT_DIR=$(dirname $(realpath $0))
BAZEL_FLAGS="--config=debug $@"
bazel build ${BAZEL_FLAGS}  //...

BIN_DIR="$(bazel info ${BAZEL_FLAGS} bazel-bin)"
echo "BIN_DIR=${BIN_DIR}"
EXTENSIONS="$(cat ${SCRIPT_DIR}/extensions.lst)"
#extensions/hello_world/libgxf_hello_world.so
for ext in ${EXTENSIONS}; do
  ln -sf -v ${BIN_DIR}/extensions/${ext}/libgxf_${ext}.so ${SCRIPT_DIR}/lib/libgxf_${ext}.so
done

